CREATE OR REPLACE FORCE VIEW "V_CONTROLLO_DISPACC_UNITA_ORGANIZZATIVA" ("CD_UNITA_ORGANIZZATIVA", "TOT_FATTURE", "TOT_DOCUMENTI_GENERICI", "TOT_ACCERTAMENTO_ASSOCIATO_CALCOLATO", "TOT_ACCERTAMENTO_ASSOCIATO", "TOT_ACCERTAMENTO_DA_ASSOCIARE") AS
  SELECT CD_UNITA_ORGANIZZATIVA,
         SUM(TOT_FATTURE) TOT_FATTURE,
         SUM(TOT_DOCUMENTI_GENERICI) TOT_DOCUMENTI_GENERICI,
         SUM(TOT_FATTURE) + SUM(TOT_DOCUMENTI_GENERICI) TOT_ACCERTAMENTO_ASSOCIATO_CALCOLATO,
         SUM(TOT_ACCERTAMENTO_ASSOCIATO) TOT_ACCERTAMENTO_ASSOCIATO,
         SUM(TOT_ACCERTAMENTO_DA_ASSOCIARE) TOT_ACCERTAMENTO_DA_ASSOCIARE
  FROM V_CONTROLLO_DISPACC_DETAIL
GROUP BY CD_UNITA_ORGANIZZATIVA;