CREATE OR REPLACE FORCE VIEW "V_CONTROLLO_ORDINE_ACQ_CONSEGNA" ("CD_CDS", "CD_UNITA_OPERATIVA", "ESERCIZIO", "CD_NUMERATORE", "NUMERO", "RIGA", "CONSEGNA", "CD_BENE_SERVIZIO_ORDINE", "UNITA_MISURA_MINIMA", "UNITA_MISURA_ORDINE", "COEF_CONV_ORDINE", "QUANTITA_ORDINE", "PERCENTUALE_IVA", "PREZZO_UNITARIO_ORDINE", "PREZZO_UNITARIO_SCONTATO_ORDINE", "PREZZO_UNITARIO_SCONTATO_ORDINE_IVATO", "STATO_CONSEGNA", "CD_CDS_EVASIONE", "CD_MAGAZZINO_EVASIONE", "ESERCIZIO_EVASIONE", "CD_NUMERATORE_EVASIONE", "NUMERO_EVASIONE", "RIGA_EVASIONE", "QUANTITA_EVASA_EVASIONE", "QUANTITA_EVASA_CALCOLATA", "STATO_EVASIONE", "PG_CARICO_MAGAZZINO", "STATO_CARICO_MAGAZZINO", "UNITA_MISURA_CARICO_MAGAZZINO", "COEF_CONV_CARICO_MAGAZZINO", "QUANTITA_CARICO_MAGAZZINO", "PREZZO_UNITARIO_CARICO_MAGAZZINO", "PREZZO_UNITARIO_CARICO_MAGAZZINO_CALCOLATO", "TIPO_CONSEGNA", "PG_SCARICO_MAGAZZINO", "STATO_SCARICO_MAGAZZINO", "UNITA_MISURA_SCARICO_MAGAZZINO", "COEF_CONV_SCARICO_MAGAZZINO", "QUANTITA_SCARICO_MAGAZZINO", "PREZZO_UNITARIO_SCARICO_MAGAZZINO", "PREZZO_UNITARIO_SCARICO_MAGAZZINO_CALCOLATO", "CD_CDS_LOTTO", "CD_MAGAZZINO_LOTTO", "ESERCIZIO_LOTTO", "CD_NUMERATORE_LOTTO", "PG_LOTTO", "CD_BENE_SERVIZIO_LOTTO", "QUANTITA_CARICO_LOTTO", "QUANTITA_CARICO_LOTTO_CALCOLATO", "VALORE_UNITARIO_LOTTO", "VALORE_UNITARIO_LOTTO_CALCOLATO", "GIACENZA_LOTTO", "GIACENZA_LOTTO_CALCOLATO", "STATO_FATTURA_CONSEGNA", "CD_CDS_FATTURA", "CD_UNITA_ORGANIZZATIVA_FATTURA", "ESERCIZIO_FATTURA", "PG_FATTURA_PASSIVA", "PROGRESSIVO_RIGA_FATTURA", "PREZZO_UNITARIO_SCONTATO_FATTURA", "PREZZO_UNITARIO_SCONTATO_FATTURA_IVATO") AS
  SELECT x.CD_CDS, x.CD_UNITA_OPERATIVA, x.ESERCIZIO, x.CD_NUMERATORE, x.NUMERO, x.RIGA, x.CONSEGNA, x.CD_BENE_SERVIZIO_ORDINE, x.UNITA_MISURA_MINIMA,
         x.UNITA_MISURA_ORDINE, x.COEF_CONV_ORDINE, x.QUANTITA_ORDINE, x.PERCENTUALE_IVA, x.PREZZO_UNITARIO_ORDINE, x.PREZZO_UNITARIO_SCONTATO_ORDINE,
         x.PREZZO_UNITARIO_SCONTATO_ORDINE_IVATO, x.STATO_CONSEGNA, x.CD_CDS_EVASIONE, x.CD_MAGAZZINO_EVASIONE, x.ESERCIZIO_EVASIONE, x.CD_NUMERATORE_EVASIONE,
         x.NUMERO_EVASIONE, x.RIGA_EVASIONE, x.QUANTITA_EVASA_EVASIONE,
         ROUND(x.QUANTITA_CARICO_MAGAZZINO*x.COEF_CONV_CARICO_MAGAZZINO/x.COEF_CONV_ORDINE,5) QUANTITA_EVASA_CALCOLATA,
         x.STATO_EVASIONE, x.PG_CARICO_MAGAZZINO, x.STATO_CARICO_MAGAZZINO, x.UNITA_MISURA_CARICO_MAGAZZINO, x.COEF_CONV_CARICO_MAGAZZINO,
         x.QUANTITA_CARICO_MAGAZZINO, x.PREZZO_UNITARIO_CARICO_MAGAZZINO,
         ROUND(x.PREZZO_UNITARIO_SCONTATO_ORDINE_IVATO*x.COEF_CONV_CARICO_MAGAZZINO/x.COEF_CONV_ORDINE,6) PREZZO_UNITARIO_CARICO_MAGAZZINO_CALCOLATO,
         x.TIPO_CONSEGNA, x.PG_SCARICO_MAGAZZINO, x.STATO_SCARICO_MAGAZZINO, x.UNITA_MISURA_SCARICO_MAGAZZINO, x.COEF_CONV_SCARICO_MAGAZZINO,
         x.QUANTITA_SCARICO_MAGAZZINO, x.PREZZO_UNITARIO_SCARICO_MAGAZZINO,
         ROUND(x.PREZZO_UNITARIO_SCONTATO_ORDINE_IVATO*x.COEF_CONV_SCARICO_MAGAZZINO/x.COEF_CONV_ORDINE,6) PREZZO_UNITARIO_SCARICO_MAGAZZINO_CALCOLATO,
         x.CD_CDS_LOTTO, x.CD_MAGAZZINO_LOTTO, x.ESERCIZIO_LOTTO, x.CD_NUMERATORE_LOTTO, x.PG_LOTTO, x.CD_BENE_SERVIZIO_LOTTO, x.QUANTITA_CARICO_LOTTO,
         CASE WHEN x.STATO_EVASIONE='ANN'
              THEN 0
              ELSE x.QUANTITA_CARICO_MAGAZZINO*x.COEF_CONV_CARICO_MAGAZZINO
              END QUANTITA_CARICO_LOTTO_CALCOLATO,
         x.VALORE_UNITARIO_LOTTO,
         CASE WHEN x.CD_CDS_FATTURA IS NOT NULL
		      THEN ROUND(ROUND(x.PREZZO_UNITARIO_SCONTATO_FATTURA_IVATO*x.COEF_CONV_CARICO_MAGAZZINO/x.COEF_CONV_ORDINE,6)/x.COEF_CONV_CARICO_MAGAZZINO,6)
			  ELSE ROUND(ROUND(x.PREZZO_UNITARIO_SCONTATO_ORDINE_IVATO*x.COEF_CONV_CARICO_MAGAZZINO/x.COEF_CONV_ORDINE,6)/x.COEF_CONV_CARICO_MAGAZZINO,6)
			  END VALORE_UNITARIO_LOTTO_CALCOLATO,
		 x.GIACENZA_LOTTO,
		 CASE WHEN x.STATO_EVASIONE='ANN' OR x.TIPO_CONSEGNA='TRA' THEN 0 ELSE x.GIACENZA_LOTTO END GIACENZA_LOTTO_CALCOLATO,
		 x.STATO_FATT STATO_FATTURA_CONSEGNA, x.CD_CDS_FATTURA, x.CD_UNITA_ORGANIZZATIVA_FATTURA, x.ESERCIZIO_FATTURA, x.PG_FATTURA_PASSIVA,
         x.PROGRESSIVO_RIGA_FATTURA,
		 CASE WHEN x.CD_CDS_FATTURA IS NOT NULL THEN x.PREZZO_UNITARIO_SCONTATO_FATTURA ELSE NULL END PREZZO_UNITARIO_SCONTATO_FATTURA,
		 CASE WHEN x.CD_CDS_FATTURA IS NOT NULL THEN x.PREZZO_UNITARIO_SCONTATO_FATTURA_IVATO ELSE NULL END PREZZO_UNITARIO_SCONTATO_FATTURA_IVATO
  FROM (SELECT oac.CD_CDS, oac.CD_UNITA_OPERATIVA, oac.ESERCIZIO, oac.CD_NUMERATORE, oac.NUMERO, oac.RIGA, oac.CONSEGNA, bs.CD_BENE_SERVIZIO CD_BENE_SERVIZIO_ORDINE,
               bs.UNITA_MISURA UNITA_MISURA_MINIMA, oar.CD_UNITA_MISURA UNITA_MISURA_ORDINE, oar.COEF_CONV COEF_CONV_ORDINE, oac.QUANTITA QUANTITA_ORDINE,
               vi.PERCENTUALE PERCENTUALE_IVA, oar.PREZZO_UNITARIO PREZZO_UNITARIO_ORDINE,
               ROUND(oar.PREZZO_UNITARIO*((100-NVL(oar.SCONTO1,0))/100)*((100-NVL(oar.SCONTO2,0))/100)*((100-NVL(oar.SCONTO3,0))/100),6) PREZZO_UNITARIO_SCONTATO_ORDINE,
               ROUND(ROUND(oar.PREZZO_UNITARIO*((100-NVL(oar.SCONTO1,0))/100)*((100-NVL(oar.SCONTO2,0))/100)*((100-NVL(oar.SCONTO3,0))/100),6)*(1+(vi.PERCENTUALE/100)), 6) PREZZO_UNITARIO_SCONTATO_ORDINE_IVATO,
               oac.STATO STATO_CONSEGNA, eor.CD_CDS CD_CDS_EVASIONE, eor.CD_MAGAZZINO CD_MAGAZZINO_EVASIONE, eor.ESERCIZIO ESERCIZIO_EVASIONE,
               eor.CD_NUMERATORE_MAG CD_NUMERATORE_EVASIONE, eor.NUMERO NUMERO_EVASIONE, eor.RIGA RIGA_EVASIONE, eor.QUANTITA_EVASA QUANTITA_EVASA_EVASIONE,
               eor.STATO STATO_EVASIONE, mm.PG_MOVIMENTO PG_CARICO_MAGAZZINO, mm.STATO STATO_CARICO_MAGAZZINO, mm.CD_UNITA_MISURA UNITA_MISURA_CARICO_MAGAZZINO,
               mm.COEFF_CONV COEF_CONV_CARICO_MAGAZZINO, mm.QUANTITA QUANTITA_CARICO_MAGAZZINO, mm.PREZZO_UNITARIO PREZZO_UNITARIO_CARICO_MAGAZZINO,
               oac.TIPO_CONSEGNA, mm2.PG_MOVIMENTO PG_SCARICO_MAGAZZINO, mm2.STATO STATO_SCARICO_MAGAZZINO, mm2.CD_UNITA_MISURA UNITA_MISURA_SCARICO_MAGAZZINO,
               mm2.COEFF_CONV COEF_CONV_SCARICO_MAGAZZINO, mm2.QUANTITA QUANTITA_SCARICO_MAGAZZINO, mm2.PREZZO_UNITARIO PREZZO_UNITARIO_SCARICO_MAGAZZINO,
               lm.CD_CDS CD_CDS_LOTTO, lm.CD_MAGAZZINO CD_MAGAZZINO_LOTTO, lm.ESERCIZIO ESERCIZIO_LOTTO, lm.CD_NUMERATORE_MAG CD_NUMERATORE_LOTTO, lm.PG_LOTTO,
               lm.CD_BENE_SERVIZIO CD_BENE_SERVIZIO_LOTTO, lm.QUANTITA_CARICO QUANTITA_CARICO_LOTTO, lm.VALORE_UNITARIO VALORE_UNITARIO_LOTTO,
               lm.GIACENZA GIACENZA_LOTTO, CASE WHEN eor.STATO != 'ANN' THEN oac.STATO_FATT ELSE NULL END STATO_FATT, fo.CD_CDS CD_CDS_FATTURA,
               fo.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_FATTURA, fo.ESERCIZIO ESERCIZIO_FATTURA, fo.PG_FATTURA_PASSIVA,
               fo.PROGRESSIVO_RIGA PROGRESSIVO_RIGA_FATTURA, nvl(fo.PREZZO_UNITARIO_RETT, oar.PREZZO_UNITARIO) PREZZO_UNITARIO_FATTURA,
               ROUND(nvl(fo.PREZZO_UNITARIO_RETT, oar.PREZZO_UNITARIO)*((100-NVL(nvl(fo.SCONTO1_RETT, oar.SCONTO1),0))/100)*
               ((100-NVL(nvl(fo.SCONTO2_RETT, oar.SCONTO2),0))/100)*((100-NVL(nvl(fo.SCONTO3_RETT, oar.SCONTO3),0))/100),6) PREZZO_UNITARIO_SCONTATO_FATTURA,
               nvl(vir.PERCENTUALE, vi.PERCENTUALE) PERCENTUALE_IVA_FATTURA,
			   ROUND(ROUND(nvl(fo.PREZZO_UNITARIO_RETT, oar.PREZZO_UNITARIO)*((100-NVL(nvl(fo.SCONTO1_RETT, oar.SCONTO1),0))/100)*((100-NVL(nvl(fo.SCONTO2_RETT, oar.SCONTO2),0))/100)*
			   ((100-NVL(nvl(fo.SCONTO3_RETT, oar.SCONTO3),0))/100),6)*(1+(nvl(vir.PERCENTUALE, vi.PERCENTUALE)/100)), 6) PREZZO_UNITARIO_SCONTATO_FATTURA_IVATO
        FROM ORDINE_ACQ_CONSEGNA oac
		LEFT JOIN ORDINE_ACQ_RIGA oar ON oar.CD_CDS = oac.CD_CDS AND oar.CD_UNITA_OPERATIVA = oac.CD_UNITA_OPERATIVA
		AND oar.ESERCIZIO = oac.ESERCIZIO AND oar.CD_NUMERATORE = oac.CD_NUMERATORE AND oar.NUMERO = oac.NUMERO
		AND oar.RIGA = oac.RIGA
		LEFT JOIN BENE_SERVIZIO bs ON bs.CD_BENE_SERVIZIO = oar.CD_BENE_SERVIZIO
		LEFT JOIN VOCE_IVA vi ON vi.CD_VOCE_IVA = oar.CD_VOCE_IVA
		LEFT JOIN EVASIONE_ORDINE_RIGA eor ON eor.CD_CDS_ORDINE = oac.CD_CDS AND eor.CD_UNITA_OPERATIVA = oac.CD_UNITA_OPERATIVA
		AND eor.ESERCIZIO_ORDINE = oac.ESERCIZIO AND eor.CD_NUMERATORE_ORDINE = oac.CD_NUMERATORE AND eor.NUMERO_ORDINE = oac.NUMERO
		AND eor.RIGA_ORDINE = oac.RIGA AND eor.CONSEGNA = oac.CONSEGNA
		LEFT JOIN MOVIMENTI_MAG mm ON mm.PG_MOVIMENTO = eor.ID_MOVIMENTI_MAG
		LEFT JOIN MOVIMENTI_MAG mm2 ON mm2.PG_MOVIMENTO = mm.PG_MOVIMENTO_RIF
		LEFT JOIN LOTTO_MAG lm ON lm.CD_CDS = mm.CD_CDS_LOTTO AND lm.CD_MAGAZZINO = mm.CD_MAGAZZINO_LOTTO AND lm.ESERCIZIO = mm.ESERCIZIO_LOTTO
		AND lm.CD_NUMERATORE_MAG = mm.CD_NUMERATORE_LOTTO AND lm.PG_LOTTO = mm.PG_LOTTO
		LEFT JOIN FATTURA_ORDINE fo ON eor.STATO != 'ANN' AND fo.CD_CDS_ORDINE = oac.CD_CDS AND fo.CD_UNITA_OPERATIVA = oac.CD_UNITA_OPERATIVA
		AND fo.ESERCIZIO_ORDINE = oac.ESERCIZIO AND fo.CD_NUMERATORE = oac.CD_NUMERATORE AND fo.NUMERO = oac.NUMERO
		AND fo.RIGA = oac.RIGA AND fo.CONSEGNA = oac.CONSEGNA
		LEFT JOIN VOCE_IVA vir ON vir.CD_VOCE_IVA = fo.CD_VOCE_IVA_RETT
		WHERE oac.QUANTITA!=0) x;