CREATE OR REPLACE FORCE VIEW "V_CONTROLLO_DISP_OBBLIGAZIONE_SCADENZARIO" ("CD_UNITA_ORGANIZZATIVA", "ESERCIZIO_OBBLIGAZIONE", "ESERCIZIO_ORI_OBBLIGAZIONE", "CD_CDS_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "TOT_ORDINE_IMPEGNO_STESSA_UO", "TOT_ORDINE_IMPEGNO_ALTRA_UO", "TOT_FATTURE_ORDINI", "TOT_FATTURE_NO_ORDINI", "TOT_COMPENSI", "TOT_DOCUMENTI_GENERICI", "TOT_IMPEGNO_ASSOCIATO_CALCOLATO", "TOT_IMPEGNO_ASSOCIATO", "TOT_IMPEGNO_DA_ASSOCIARE") AS
  SELECT CD_UNITA_ORGANIZZATIVA, ESERCIZIO_OBBLIGAZIONE, ESERCIZIO_ORI_OBBLIGAZIONE, CD_CDS_OBBLIGAZIONE, PG_OBBLIGAZIONE, PG_OBBLIGAZIONE_SCADENZARIO,
  		SUM(TOT_ORDINE_IMPEGNO_STESSA_UO) TOT_ORDINE_IMPEGNO_STESSA_UO,
  		SUM(TOT_ORDINE_IMPEGNO_ALTRA_UO) TOT_ORDINE_IMPEGNO_ALTRA_UO,
        SUM(TOT_FATTURE_ORDINI) TOT_FATTURE_ORDINI,
        SUM(TOT_FATTURE_NO_ORDINI) TOT_FATTURE_NO_ORDINI,
        SUM(TOT_COMPENSI) TOT_COMPENSI,
        SUM(TOT_DOCUMENTI_GENERICI) TOT_DOCUMENTI_GENERICI,
        SUM(TOT_ORDINE_IMPEGNO_STESSA_UO) + SUM(TOT_ORDINE_IMPEGNO_ALTRA_UO) + SUM(TOT_FATTURE_NO_ORDINI) + SUM(TOT_COMPENSI) + SUM(TOT_DOCUMENTI_GENERICI) TOT_IMPEGNO_ASSOCIATO_CALCOLATO,
        SUM(TOT_IMPEGNO_ASSOCIATO) TOT_IMPEGNO_ASSOCIATO,
        SUM(TOT_IMPEGNO_DA_ASSOCIARE) TOT_IMPEGNO_DA_ASSOCIARE
  FROM V_CONTROLLO_DISP_DETAIL
  GROUP BY CD_UNITA_ORGANIZZATIVA, ESERCIZIO_OBBLIGAZIONE, ESERCIZIO_ORI_OBBLIGAZIONE, CD_CDS_OBBLIGAZIONE, PG_OBBLIGAZIONE, PG_OBBLIGAZIONE_SCADENZARIO;