CREATE OR REPLACE FORCE VIEW CUPPROGETTI AS
	SELECT DISTINCT PG_PROGETTO,CD_CUP,ESERCIZIO  FROM CONTRATTO c  WHERE c.PG_PROGETTO IS NOT NULL AND c.CD_CUP IS NOT NULL AND c.stato = 'D' GROUP BY PG_PROGETTO,CD_CUP,ESERCIZIO 
	UNION ALL
	SELECT DISTINCT PG_PROGETTO,CD_CUP,ESERCIZIO  FROM CONTRATTO c  WHERE c.PG_PROGETTO IS NOT NULL AND c.CD_CUP IS NULL AND c.stato = 'D' GROUP BY PG_PROGETTO,CD_CUP,ESERCIZIO  ORDER BY PG_PROGETTO ;
